name: Update Deadlines

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Executar script de atualização
        run: python .github/workflows/update_deadlines.py

      - name: Commit e Push das alterações
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update deadlines [automated]"
