name: Update Project Timelines
on:
  schedule:
    - cron: '0 * * * *' # Roda a cada hora
  workflow_dispatch:      # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Update README Table
        run: |
          python .github/scripts/update_table.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs: update project timelines" || exit 0
          git push
